global:
  scrape_interval: 10s

scrape_configs:
  - job_name: tempsens-app
    scrape_interval: 10s
    metrics_path: /metrics/app
    static_configs:
      - targets:
        - 172.28.32.1:2112

  - job_name: tempsens-process
    scrape_interval: 1m
    metrics_path: /metrics/process
    static_configs:
      - targets:
        - 172.28.32.1:2112

  - job_name: prometheus
    scrape_interval: 5m
    static_configs:
      - targets:
        - prometheus:9090